
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// IMPORTANT: These values are automatically injected by Lovable at runtime
// Do not modify these values directly - they will be replaced with the correct values
const SUPABASE_URL = "https://abkrqwefzjxdtzumwhev.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFia3Jxd2Vmemp4ZHR6dW13aGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MTQ0ODQsImV4cCI6MjA1MDk5MDQ4NH0.-FCaINteM5v5Yq25uZ1_bq9HsF4_3mHFP-0fKWmEg3Y";

const getSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
};

export const supabase = getSupabaseClient();
