
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getSupabaseClient = () => {
  // Get URL and key from window.env (injected by Lovable)
  const SUPABASE_URL = window.env?.SUPABASE_URL;
  const SUPABASE_ANON_KEY = window.env?.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('Missing Supabase credentials. Make sure to set SUPABASE_URL and SUPABASE_ANON_KEY in your environment.');
    throw new Error('Missing Supabase credentials');
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
};

export const supabase = getSupabaseClient();
